const siteWideChecks = {
  "Local SEO": [
    "Address & Phone Shown on Website",
    "Local Business Schema",
    "Google Business Profile Identified",
    "Google Business Profile Completeness",
    "Google Reviews",
  ],
  "Technology Results": [
    "Technology List",
    "Server IP Address",
    "DNS Servers",
    "Web server",
    "Charset",
    "DMARC Record",
    "SPF Record",
  ],
  "Keyword Rankings": [
    "Top Keyword Rankings",
    "Total Traffic From Search",
    "Keyword Positions",
  ],
  Links: [
    "Backlink Summary",
    "Top Backlinks",
    "Top Pages by Backlinks",
    "Top Anchors by Backlinks",
    "Top Geographies",
  ],
  "Performance Results": [
    "Page Speed",
    "Download Page Size",
    "Website Compression (Gzip, Deflate, Brotli)",
    "Number of Objects Loaded",
    "Google Accelerated Mobile Pages (AMP)",
    "Javasctipt Errors",
    "HTTP2 Usage",
    "Image Optimization",
    "Minification",
    "Deprecated HTML",
    "Inline Styles",
  ],
  "Social Results": [
    "Facebook Page Linked",
    "X (Formerly Twitter) Account Linked",
    "X Cards",
    "Instagram Linked",
    "Youtube Channel Linked",
    "Youtube Channel Activity",
    "LinkedIn Page Linked",
  ],
};

const pageLevelChecks = {
  "On-Page SEO Results": [
    "Title Tag",
    "Target Keyword in Title Tag",
    "Meta Description Tag",
    "Target Keyword in Meta Description Tag",
    "SERP Snippet Preview",
    "Hreflang Tag",
    "Lang attribute in Header Tag",
    "H1 Header Tag Usage",
    "Target Keyword in H1",
    "H2-H6 Header Tag Usage",
    "Keyword Consistency",
    "Amount of Content",
    "Image Alt Attributes",
    "Target Keyword in Image Alt Attributes",
    "Canonical Tag",
    "Noindex Tag Test",
    "Noindex Header Test",
    "SSL Enabled",
    "XML Sitemaps", // Some prefer this as site-wide, but many sites use per-page sitemaps
    "Analytics",
    "Robots.txt",
    "Blocked by Robots.txt",
  ],
  Links: ["On-Page Links", "Friendly Links", "Target Keyword in URL"],
  "Usability Results": [
    "Device Rendering",
    "Use of Mobile Viewports",
    "Google's Core Web Vitals",
    "Page Speed Insights - Mobile",
    "Page Speed Insights - Desktop",
    "Flash Used?",
    "iFrames Used?",
    "Favicon",
    "Email Privacy",
    "Legible Font Sizes",
    "Top Target Sizing",
  ],
};

module.exports = { siteWideChecks, pageLevelChecks };
